### PR TITLE
请不要公开发布习题解答

### PR DESCRIPTION
**Pull request by liyishuai**
根据[前言](https://softwarefoundations.cis.upenn.edu/current/Preface.html#lab12)章节，习题解答不应公开上传。请将其移至私有代码库。

### CODE REVIEW

**Comment by eccstartup** [comment]
Please get a PhD degree first to instruct me.

**Comment by bcpierce00** [comment]
As Yishuai says, the SF authors respectfully request that solutions not be posted in public places.  The reasons for this are explained in the Preface.  Thank you!  

Benjamin Pierce

**Comment by eccstartup** [comment]
@bcpierce00 A friend hinted me @liyishuai has opened fire to me on this somewhere, so I get up at 3 a.m. to resolve this. But I am sorry, I hold a different opinion about this advice. 
> Please do not post solutions to the exercises in ~~_a_~~ public places

I forked this because I was in trouble and had not access to any aid.

Solutions are helpful for those who want to learn themselves, or could not find an immediate instructor like you. When they get stuck, solutions are helpful tips to keep them move on. The Internet is an open space, and everyone should have access to the solution to any problem if is was solved by others. So, I prefer to keep it here, and add one line
> Please do not copy the solutions if you are doing your homework.

I don't rule out the case when a student copies the answers from this repo without doing it himself/herself. But that is the student not this repo to be blame.

If you still think it is **NOT OK** to post it here. I would remove it.

**Comment by qinkunbao** [comment]
哈哈，太好玩了，老板替学生出头了。

**Comment by liyishuai** [comment]
Thank you for responding to Dr. Pierce's advice seriously.
After a recent discussion during DeepSpec Summer School, many Coq users are invited to the [StackOverflow Coq community](https://stackoverflow.com/questions/tagged/coq). I hold the belief that interactive instructions are more helpful than static solutions, and look forward to your contribution.

**Comment by lonyle** [comment]
围观围观

**Comment by xnning** [comment]
I personally hold a similar opinion as @eccstartup.

The thing is, forbidding a public repo like this is only to prevent the students in the class to copy answers, however, there are many students in the internet that can only learn this book by themselves. Also, students that want to copy answers can always copy answers from somewhere (e.g. other student's answers).

Yes of course interactive instructions in a platform like StackOverflow is more helpful but I believe it is better not to waste other people's time on repeating answering similar or perhaps silly questions while it is easy to learn by oneself from static solutions immediately. Worse, students can also copy answers from StackOverflow.

I hold a similar repo (solutions for SF) and also get a similar issue opened by @liyishuai. I haven't dealt with it yet. But anyway, I respect authors' will. I could make my repo private according to the decision here.

**Pull request closed without merging**
